add retry logic to Makefile execution in CI workflow for improved reliability

diff --git a/.github/workflows/packer-builds-app.yml b/.github/workflows/packer-builds-app.yml
--- a/.github/workflows/packer-builds-app.yml
+++ b/.github/workflows/packer-builds-app.yml
@@ -65,6 +65,19 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4.1.1
         
-      - name: Run Makefile
-        run: make ${{ matrix.image_type }}
-      
+      - name: Run Makefile with retries
+        shell: bash
+        run: |
+          max_attempts=3
+          attempt=1
+          until make ${{ matrix.image_type }} || [ $attempt -eq $max_attempts ]
+          do
+            echo "Attempt $attempt failed! Retrying in 30 seconds..."
+            attempt=$(( attempt + 1 ))
+            sleep 30
+          done
+          
+          if [ $attempt -eq $max_attempts ] && ! make ${{ matrix.image_type }}; then
+            echo "All $max_attempts attempts failed"
+            exit 1
+          fi
